STATE_KEY_USER = 'cur_user'
STATE_KEY_SECTION = 'cur_section'

State = {
    STATE_KEY_USER: None,
    STATE_KEY_SECTION: None,
}

STATE_SECTION_MAIN_EXPENSES = 1
STATE_SECTION_MAIN_INCOMES = 2
STATE_SECTION_ADMIN_USERS = 3
